Check for sum directly

diff --git a/proxy-chrome b/proxy-chrome
--- a/proxy-chrome
+++ b/proxy-chrome
@@ -46,12 +46,16 @@ TEMP_DIR=$(mktemp -d "$BASE_TEMP_DIR/proxy-tdir.XXXXXXX")
 function clean_up {
 	log "Local state of $(du -hs $TEMP_DIR | cut -f 1)"
 	log "Cleaning up"
-	if [[ "$UNAME" == 'Darwin' ]]; then
-		SRMFLAGS='-szrf'
+	if which srm; then
+		if [[ "$UNAME" == 'Darwin' ]]; then
+			SRMFLAGS='-szrf'
+		else
+			SRMFLAGS='-sllrf'
+		fi
+		srm $SRMFLAGS "$TEMP_DIR" || error "failed to clean up '$TEMP_DIR'"
 	else
-		SRMFLAGS='-sllrf'
-	fi
-	srm $SRMFLAGS "$TEMP_DIR" || log "srm not found, using non-secure delete"; rm -rf "$TEMP_DIR" || error "failed to clean up '$TEMP_DIR'"
+		log "srm not found, using non-secure delete"
+		rm -rf "$TEMP_DIR" || error "failed to clean up '$TEMP_DIR'"
 }
 _on_exit clean_up
 
